version: "3.7"

services:
  scrapper:
    build:
      context: .
    ports:
      - "8000:8000"  
    volumes:
      - ./scrapper:/scrapper
    command: sh -c "python manage.py runserver 0.0.0.0:8000"